LATEX_TEMP= """\\newcommand{\Customer}{%s}
\\newcommand{\Date}{%s}
\\newcommand{\TicketNum}{%s}
\\newcommand{\PaidState}{%s}
\\newcommand{\CheckNum}{%s}
\\newcommand{\Comment}{%s}
\\newcommand{\SmallBags}{%d}
\\newcommand{\PriceSmallBags}{%.2f}
\\newcommand{\TotalSmallBags}{%.2f}
\\newcommand{\BigBags}{%d}
\\newcommand{\PriceBigBags}{%.2f}
\\newcommand{\TotalBigBags}{%.2f}
\\newcommand{\setColorBags}{%s}
\\newcommand{\SmallBlock}{%d}
\\newcommand{\PriceSmallBlock}{%.2f}
\\newcommand{\TotalSmallBlock}{%.2f}
\\newcommand{\LargeBlock}{%d}
\\newcommand{\PriceLargeBlock}{%.2f}
\\newcommand{\TotalLargeBlock}{%.2f}
\\newcommand{\setColorBlocks}{%s}
\\newcommand{\VendorRent}{%d}
\\newcommand{\RateVendorRent}{%.2f}
\\newcommand{\TotalVendorRent}{%.2f}
\\newcommand{\setColorVendor}{%s}
\\newcommand{\Storage}{%d}
\\newcommand{\PriceStorage}{%.2f}
\\newcommand{\TotalStorage}{%.2f}
\\newcommand{\setColorStorage}{%s}
\\newcommand{\Freight}{%d}
\\newcommand{\PriceFreight}{%.2f}
\\newcommand{\TotalFreight}{%.2f}
\\newcommand{\setColorFreight}{%s}
\\newcommand{\Other}{%d}
\\newcommand{\PriceOther}{%.2f}
\\newcommand{\TotalOther}{%.2f}
\\newcommand{\setColorOther}{%s}
\\newcommand{\TicketTotal}{%.2f}
"""
