import { Ticket } from './ticket';

export var TICKETS: Ticket[] = [
    new Ticket(  "John Doe", 
                 "2016-09-15", 
                 "check", 
                 "lajsdfasfd",
                 'foo', 
                 '', 
                 {price:15, qty: 5},
                 {price:19, qty: 8},
                 {price:1, qty: 23},
                 {price:0, qty: 9},
                 {price:0, qty: 0},
                 {price:0, qty: 0},
                 {price:3.52, qty: 0},
                 {price:0, qty: 0},
                 155.2),
    new Ticket(  "Bob Dole", 
                 "2016-09-10", 
                 "check", 
                 "jcklsadcj",
                 'foo1', 
                 '', 
                 {price:15, qty: 5},
                 {price:19, qty: 8},
                 {price:1, qty: 23},
                 {price:0, qty: 9},
                 {price:0, qty: 0},
                 {price:0, qty: 0},
                 {price:3.52, qty: 0},
                 {price:0, qty: 0},
                 155.2),

    new Ticket(  "Bob Dole", 
                 "2016-09-10", 
                 "check", 
                 "jcklsadcj",
                 'foo1', 
                 '', 
                 {price:15, qty: 5},
                 {price:19, qty: 8},
                 {price:1, qty: 23},
                 {price:0, qty: 9},
                 {price:0, qty: 0},
                 {price:0, qty: 0},
                 {price:3.52, qty: 0},
                 {price:0, qty: 0},
                 155.2),

    new Ticket(  "Bob Dole", 
                 "2016-09-10", 
                 "check", 
                 "jcklsadcj",
                 'foo1', 
                 '', 
                 {price:15, qty: 5},
                 {price:19, qty: 8},
                 {price:1, qty: 23},
                 {price:0, qty: 9},
                 {price:0, qty: 0},
                 {price:0, qty: 0},
                 {price:3.52, qty: 0},
                 {price:0, qty: 0},
                 155.2),

    new Ticket(  "Bob Dole", 
                 "2016-09-10", 
                 "check", 
                 "jcklsadcj",
                 'foo1', 
                 '', 
                 {price:15, qty: 5},
                 {price:19, qty: 8},
                 {price:1, qty: 23},
                 {price:0, qty: 9},
                 {price:0, qty: 0},
                 {price:0, qty: 0},
                 {price:3.52, qty: 0},
                 {price:0, qty: 0},
                 155.2),

    new Ticket(  "Bob Dole", 
                 "2016-09-10", 
                 "check", 
                 "jcklsadcj",
                 'foo1', 
                 '', 
                 {price:15, qty: 5},
                 {price:19, qty: 8},
                 {price:1, qty: 23},
                 {price:0, qty: 9},
                 {price:0, qty: 0},
                 {price:0, qty: 0},
                 {price:3.52, qty: 0},
                 {price:0, qty: 0},
                 155.2),

    new Ticket(  "Bob Dole", 
                 "2016-09-10", 
                 "check", 
                 "jcklsadcj",
                 'foo1', 
                 '', 
                 {price:15, qty: 5},
                 {price:19, qty: 8},
                 {price:1, qty: 23},
                 {price:0, qty: 9},
                 {price:0, qty: 0},
                 {price:0, qty: 0},
                 {price:3.52, qty: 0},
                 {price:0, qty: 0},
                 155.2),

    new Ticket(  "Bob Dole", 
                 "2016-09-10", 
                 "check", 
                 "jcklsadcj",
                 'foo1', 
                 '', 
                 {price:15, qty: 5},
                 {price:19, qty: 8},
                 {price:1, qty: 23},
                 {price:0, qty: 9},
                 {price:0, qty: 0},
                 {price:0, qty: 0},
                 {price:3.52, qty: 0},
                 {price:0, qty: 0},
                 155.2)
];
